import { 
  Procedure, 
  TrainingRecord, 
  Assessment, 
  RespondentStatus, 
  DashboardMetrics, 
  ChartSectorMetric, 
  ChartProjectionMetric 
} from '@/types';

export const INITIAL_METRICS: DashboardMetrics = {
  generalCompliance: 94.2,
  activeCertifications: 428,
  expiringIn60Days: 38,
  expiredDocuments: 12,
};

export const SECTOR_CHART_DATA: ChartSectorMetric[] = [
  { sector: 'Operacional', certificados: 142, falhas: 8 },
  { sector: 'Brascabo', certificados: 86, falhas: 4 },
  { sector: 'RDO', certificados: 64, falhas: 5 },
  { sector: 'QSMS', certificados: 52, falhas: 2 },
  { sector: 'Suprimentos', certificados: 48, falhas: 6 },
  { sector: 'Transbordo', certificados: 36, falhas: 3 },
];

export const PROJECTION_CHART_DATA: ChartProjectionMetric[] = [
  { month: 'Nov', reciclagens: 18, vencimentos: 12 },
  { month: 'Dez', reciclagens: 24, vencimentos: 15 },
  { month: 'Jan', reciclagens: 31, vencimentos: 22 },
  { month: 'Fev', reciclagens: 29, vencimentos: 18 },
  { month: 'Mar', reciclagens: 22, vencimentos: 14 },
  { month: 'Abr', reciclagens: 19, vencimentos: 11 },
];

export const INITIAL_PROCEDURES: Procedure[] = [
  {
    id: 'proc-1',
    code: 'POP-OP-014',
    name: 'Operações a Empregadeiras e Cabos Submarinos',
    sector: 'Operações Offshore',
    associatedRole: 'Operador de Convés / Guindasteiro',
    application: 'Lançamento e tração de cabos ópticos/umbilicais em embarcações DP2',
    complianceRate: 96.5,
    lastRevision: '14/09/2026',
    status: 'Ativo',
    questionsCount: 10,
    criticality: 'Alta',
    description: 'Estabelece diretrizes de segurança nas operações com empregadeiras hidráulicas e tração contínua.',
    validityMonths: 12,
  },
  {
    id: 'proc-2',
    code: 'POP-ST-002',
    name: 'Trabalho a Quente e Atmosferas Explosivas (Ex)',
    sector: 'Segurança do Trabalho',
    associatedRole: 'Técnico QSMS / Soldador Offshore',
    application: 'Permissão de Trabalho (PT), testes de explosividade e vigilância de fogo',
    complianceRate: 88.0,
    lastRevision: '02/08/2026',
    status: 'Ativo',
    questionsCount: 15,
    criticality: 'Alta',
    description: 'Protocolo de emissão de Permissão de Trabalho a Quente em zonas classificadas NR-37.',
    validityMonths: 12,
  },
  {
    id: 'proc-3',
    code: 'POP-QL-008',
    name: 'Inspeção Não Destrutiva (LP e Partículas Magnéticas)',
    sector: 'Qualidade',
    associatedRole: 'Inspetor de Qualidade / Técnico END',
    application: 'Controle de qualidade e integridade estrutural de olhais e soldas',
    complianceRate: 91.2,
    lastRevision: '19/07/2026',
    status: 'Ativo',
    questionsCount: 12,
    criticality: 'Média',
    description: 'Critérios de aceitação para ensaios não destrutivos de equipamentos de elevação de carga.',
    validityMonths: 24,
  },
  {
    id: 'proc-4',
    code: 'POP-LOG-005',
    name: 'Movimentação de Cargas em Convés e Supply Vessels',
    sector: 'Logística',
    associatedRole: 'Rigger / Sinaleiro / Marinheiro de Convés',
    application: 'Içamento dinâmico entre embarcação de apoio e plataforma fixa/FPSO',
    complianceRate: 79.4,
    lastRevision: '28/05/2026',
    status: 'Em Revisão',
    questionsCount: 8,
    criticality: 'Alta',
    description: 'Procedimento operacional para plano de rigging, limites de onda e comunicação via rádio VHF.',
    validityMonths: 12,
  },
  {
    id: 'proc-5',
    code: 'POP-TI-011',
    name: 'Redundância e Cibersegurança em Redes DP2/DP3',
    sector: 'Tecnologia',
    associatedRole: 'Operador de ROV / Oficial de Náutica',
    application: 'Sistemas SCADA de navegação, posicionamento dinâmico e telemetria',
    complianceRate: 98.1,
    lastRevision: '11/09/2026',
    status: 'Ativo',
    questionsCount: 14,
    criticality: 'Média',
    description: 'Manutenção de canais de fibra submarina e prevenção contra intrusão em redes operacionais.',
    validityMonths: 24,
  },
  {
    id: 'proc-6',
    code: 'POP-MA-003',
    name: 'Plano de Resposta a Incidentes de Óleo no Mar (PEI)',
    sector: 'Meio Ambiente',
    associatedRole: 'Coordenador QSMS / Equipe de Emergência',
    application: 'Contenção primária com barreiras oceânicas e skimmers de alta sucção',
    complianceRate: 94.0,
    lastRevision: '05/06/2026',
    status: 'Ativo',
    questionsCount: 12,
    criticality: 'Alta',
    description: 'Acionamento do Plano de Emergência Individual conforme resoluções CONAMA e IBAMA.',
    validityMonths: 12,
  },
  {
    id: 'proc-7',
    code: 'POP-RH-001',
    name: 'Embarque, Aclimatação e Integração NR-37',
    sector: 'RH',
    associatedRole: 'Todos os Colaboradores Embarcados',
    application: 'Briefing de segurança no heliponto, alarmes gerais e rota de fuga',
    complianceRate: 99.0,
    lastRevision: '20/09/2026',
    status: 'Ativo',
    questionsCount: 10,
    criticality: 'Baixa',
    description: 'Treinamento introdutório obrigatório para todo profissional antes de assumir posto no convés.',
    validityMonths: 24,
  },
  {
    id: 'proc-8',
    code: 'POP-SP-004',
    name: 'Controle de Acesso e Código ISPS em Terminais',
    sector: 'Segurança Patrimonial',
    associatedRole: 'Agente de Proteção Marítima',
    application: 'Inspeção de bagagens, detector de traços e conferência de passaportes',
    complianceRate: 85.5,
    lastRevision: '12/04/2026',
    status: 'Arquivado',
    questionsCount: 6,
    criticality: 'Baixa',
    description: 'Segurança de instalações portuárias marítimas segundo código internacional ISPS.',
    validityMonths: 12,
  },
];

export const INITIAL_TRAINING_RECORDS: TrainingRecord[] = [
  {
    id: 'rec-1',
    employeeId: 'emp-1',
    employeeName: 'Carlos Silva',
    employeeRole: 'Supervisor de Convés',
    employeeAvatar: '/images/avatar_engineer.jpg',
    sector: 'Operações Offshore',
    procedureCode: 'POP-OP-014',
    procedureName: 'Operações a Empregadeiras',
    completionDate: '15/05/2026',
    validityDate: '15/05/2027',
    daysRemaining: 221,
    complianceRate: 98,
    status: 'Certificado',
    instructor: 'Eng. Roberto Vasconcelos',
    certificateHash: 'CERT-2026-BR-9941',
  },
  {
    id: 'rec-2',
    employeeId: 'emp-2',
    employeeName: 'Ana Lima',
    employeeRole: 'Técnica de Segurança QSMS',
    employeeAvatar: '/images/avatar_inspector.jpg',
    sector: 'QSMS',
    procedureCode: 'POP-ST-002',
    procedureName: 'Trabalho a Quente e Atmosferas Ex',
    completionDate: '10/09/2025',
    validityDate: '10/09/2026',
    daysRemaining: -26,
    complianceRate: 54,
    status: 'Vencido',
    instructor: 'Espec. Marcos Tavares',
    certificateHash: 'CERT-2025-BR-1022',
  },
  {
    id: 'rec-3',
    employeeId: 'emp-3',
    employeeName: 'Pedro Alves',
    employeeRole: 'Operador de ROV Subsea',
    employeeAvatar: '/images/avatar_operator.jpg',
    sector: 'Tecnologia',
    procedureCode: 'POP-TI-011',
    procedureName: 'Redundância em Redes DP2/DP3',
    completionDate: '01/08/2026',
    validityDate: '01/08/2028',
    daysRemaining: 664,
    complianceRate: 95,
    status: 'Certificado',
    instructor: 'Msc. Danielle Fontes',
    certificateHash: 'CERT-2026-BR-8830',
  },
  {
    id: 'rec-4',
    employeeId: 'emp-4',
    employeeName: 'Marcos Vinícius',
    employeeRole: 'Rigger / Sinaleiro Offshore',
    employeeAvatar: '/images/avatar_engineer.jpg',
    sector: 'Logística',
    procedureCode: 'POP-LOG-005',
    procedureName: 'Movimentação em Supply Vessels',
    completionDate: '20/11/2025',
    validityDate: '20/11/2026',
    daysRemaining: 45,
    complianceRate: 74,
    status: 'Reciclar',
    instructor: 'Cap. Fernando Paiva',
    certificateHash: 'CERT-2025-BR-7719',
  },
  {
    id: 'rec-5',
    employeeId: 'emp-5',
    employeeName: 'Luciana Rodrigues',
    employeeRole: 'Inspetora de Qualidade NDT',
    employeeAvatar: '/images/avatar_inspector.jpg',
    sector: 'Qualidade',
    procedureCode: 'POP-QL-008',
    procedureName: 'Inspeção LP e Partículas',
    completionDate: '12/08/2024',
    validityDate: '12/08/2026',
    daysRemaining: -55,
    complianceRate: 48,
    status: 'Vencido',
    instructor: 'Eng. Marcelo Nogueira',
    certificateHash: 'CERT-2024-BR-3094',
  },
  {
    id: 'rec-6',
    employeeId: 'emp-6',
    employeeName: 'Eduardo Guedes',
    employeeRole: 'Guindasteiro Offshore',
    employeeAvatar: '/images/avatar_operator.jpg',
    sector: 'Operacional',
    procedureCode: 'POP-OP-014',
    procedureName: 'Operações a Empregadeiras',
    completionDate: '18/12/2025',
    validityDate: '18/12/2026',
    daysRemaining: 73,
    complianceRate: 76,
    status: 'Reciclar',
    instructor: 'Eng. Roberto Vasconcelos',
    certificateHash: 'CERT-2025-BR-4481',
  },
  {
    id: 'rec-7',
    employeeId: 'emp-7',
    employeeName: 'Beatriz Costa',
    employeeRole: 'Engenheira de Meio Ambiente',
    employeeAvatar: '/images/avatar_inspector.jpg',
    sector: 'Meio Ambiente',
    procedureCode: 'POP-MA-003',
    procedureName: 'Resposta a Incidentes de Óleo (PEI)',
    completionDate: '30/06/2026',
    validityDate: '30/06/2027',
    daysRemaining: 267,
    complianceRate: 99,
    status: 'Certificado',
    instructor: 'Dr. Valter Silveira',
    certificateHash: 'CERT-2026-BR-6612',
  },
  {
    id: 'rec-8',
    employeeId: 'emp-8',
    employeeName: 'Rodrigo Antunes',
    employeeRole: 'Eletricista de Força e Controle',
    employeeAvatar: '/images/avatar_engineer.jpg',
    sector: 'Operacional',
    procedureCode: 'POP-ST-002',
    procedureName: 'Trabalho a Quente e Atmosferas Ex',
    completionDate: '25/11/2025',
    validityDate: '25/11/2026',
    daysRemaining: 50,
    complianceRate: 78,
    status: 'Reciclar',
    instructor: 'Espec. Marcos Tavares',
    certificateHash: 'CERT-2025-BR-9901',
  },
];

export const INITIAL_ASSESSMENT: Assessment = {
  id: 'ass-1',
  code: 'AVAL-POP-OP-014',
  title: 'Prova de Eficácia: POP-OP-014 Operações a Empregadeiras',
  procedureCode: 'POP-OP-014',
  procedureTitle: 'Operações a Empregadeiras e Cabos Submarinos',
  questionsCount: 10,
  minScorePercent: 80,
  durationMinutes: 20,
  maxAttempts: 2,
  tokenUuid: '7b91d293-84f0-466d-a78b-3c48208aef72',
  status: 'Ativa',
  approvalRate: 94.2,
  totalSubmissions: 342,
  avgDurationMinutes: 14,
  questions: [
    {
      id: 'q-1',
      question: 'Qual é o valor máximo de tração permitido na partida suave da empregadeira sem alinhamento confirmado com a ponte de comando?',
      options: [
        '50% da capacidade nominal de tração',
        'Tração zero com freio dinâmico desativado',
        '25% da carga máxima de trabalho com autorização do Capitão/DPO',
        'Nenhum movimento é autorizado sem checagem de alinhamento visual e de rádio'
      ],
      correctOptionIndex: 3,
      explanation: 'Conforme item 4.2 do POP-OP-014, o movimento em falso ou sob carga é estritamente proibido sem liberação por canal VHF exclusivo e confirmação com o DPO.'
    },
    {
      id: 'q-2',
      question: 'Em caso de oscilação brusca do mar (pitch/roll superior a 4°), qual é a primeira ação imediata do operador da empregadeira?',
      options: [
        'Aumentar velocidade para recolher o cabo rapidamente',
        'Ativar o modo Tension Hold e notificar o supervisor de convés imediatamente',
        'Cortar o cabo com tesoura hidráulica de emergência',
        'Desligar todos os geradores auxiliares'
      ],
      correctOptionIndex: 1,
      explanation: 'O modo Tension Hold mantém a tensão de segurança estática evitando fadiga no cabo submarino até estabilização náutica.'
    },
    {
      id: 'q-3',
      question: 'Qual é o EPI adicional obrigatório para atuação no raio de curvatura da bobina de tração?',
      options: [
        'Capacete com jugular classe B e colete salva-vidas inflável homologado DPC',
        'Apenas luvas de vaqueta simples',
        'Protetor auricular tipo concha',
        'Óculos de sol polarizados'
      ],
      correctOptionIndex: 0,
      explanation: 'Em áreas de convés externo com risco de projeção de cabos e queda ao mar, o uso de colete inflável DPC com acionamento automático é obrigatório conforme NR-37.'
    }
  ],
};

export const INITIAL_RESPONDENTS: RespondentStatus[] = [
  {
    id: 'resp-1',
    employeeId: 'emp-4',
    name: 'Marcos Vinícius',
    role: 'Rigger / Sinaleiro Offshore',
    sector: 'Logística',
    scorePercent: null,
    status: 'Pendente',
    submissionDate: null,
    dueDate: '20/10/2026',
    attemptsUsed: 0,
  },
  {
    id: 'resp-2',
    employeeId: 'emp-2',
    name: 'Ana Lima',
    role: 'Técnica de Segurança QSMS',
    sector: 'QSMS',
    scorePercent: 54,
    status: 'Reprovado',
    submissionDate: '01/10/2026',
    dueDate: '10/10/2026',
    attemptsUsed: 1,
  },
  {
    id: 'resp-3',
    employeeId: 'emp-5',
    name: 'Luciana Rodrigues',
    role: 'Inspetora de Qualidade NDT',
    sector: 'Qualidade',
    scorePercent: null,
    status: 'Pendente',
    submissionDate: null,
    dueDate: '15/10/2026',
    attemptsUsed: 0,
  },
  {
    id: 'resp-4',
    employeeId: 'emp-6',
    name: 'Eduardo Guedes',
    role: 'Guindasteiro Offshore',
    sector: 'Operacional',
    scorePercent: 70,
    status: 'Em Andamento',
    submissionDate: null,
    dueDate: '22/10/2026',
    attemptsUsed: 1,
  },
  {
    id: 'resp-5',
    employeeId: 'emp-8',
    name: 'Rodrigo Antunes',
    role: 'Eletricista de Força e Controle',
    sector: 'Operacional',
    scorePercent: null,
    status: 'Pendente',
    submissionDate: null,
    dueDate: '25/10/2026',
    attemptsUsed: 0,
  },
  {
    id: 'resp-6',
    employeeId: 'emp-1',
    name: 'Carlos Silva',
    role: 'Supervisor de Convés',
    sector: 'Operações Offshore',
    scorePercent: 95,
    status: 'Entregue',
    submissionDate: '04/10/2026',
    dueDate: '10/10/2026',
    attemptsUsed: 1,
  },
];
